### ISSUE TITLE
errors during installation 

### ISSUE THREAD

**Issue by wdlv** [slicersalt/dwd#1]
Hi, I have met some problems during installation. My python is Python 3.6.8 :: Anaconda, Inc.  macOS Mojave Version 10.14.6
Below is the error message:

running install
running bdist_egg
running egg_info
creating dwd.egg-info
writing dwd.egg-info/PKG-INFO
writing dependency_links to dwd.egg-info/dependency_links.txt
writing requirements to dwd.egg-info/requires.txt
writing top-level names to dwd.egg-info/top_level.txt
writing manifest file 'dwd.egg-info/SOURCES.txt'
reading manifest file 'dwd.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'dwd.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.7-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/dwd
copying dwd/kernel_utils.py -> build/lib/dwd
copying dwd/sim_fun.py -> build/lib/dwd
copying dwd/gen_kern_dwd.py -> build/lib/dwd
copying dwd/__init__.py -> build/lib/dwd
copying dwd/utils.py -> build/lib/dwd
copying dwd/dwd.py -> build/lib/dwd
copying dwd/cv.py -> build/lib/dwd
copying dwd/kern_md.py -> build/lib/dwd
copying dwd/svm.py -> build/lib/dwd
copying dwd/viz.py -> build/lib/dwd
copying dwd/gen_dwd.py -> build/lib/dwd
creating build/bdist.macosx-10.7-x86_64
creating build/bdist.macosx-10.7-x86_64/egg
creating build/bdist.macosx-10.7-x86_64/egg/dwd
copying build/lib/dwd/kernel_utils.py -> build/bdist.macosx-10.7-x86_64/egg/dwd
copying build/lib/dwd/sim_fun.py -> build/bdist.macosx-10.7-x86_64/egg/dwd
copying build/lib/dwd/gen_kern_dwd.py -> build/bdist.macosx-10.7-x86_64/egg/dwd
copying build/lib/dwd/__init__.py -> build/bdist.macosx-10.7-x86_64/egg/dwd
copying build/lib/dwd/utils.py -> build/bdist.macosx-10.7-x86_64/egg/dwd
copying build/lib/dwd/dwd.py -> build/bdist.macosx-10.7-x86_64/egg/dwd
copying build/lib/dwd/cv.py -> build/bdist.macosx-10.7-x86_64/egg/dwd
copying build/lib/dwd/kern_md.py -> build/bdist.macosx-10.7-x86_64/egg/dwd
copying build/lib/dwd/svm.py -> build/bdist.macosx-10.7-x86_64/egg/dwd
copying build/lib/dwd/viz.py -> build/bdist.macosx-10.7-x86_64/egg/dwd
copying build/lib/dwd/gen_dwd.py -> build/bdist.macosx-10.7-x86_64/egg/dwd
byte-compiling build/bdist.macosx-10.7-x86_64/egg/dwd/kernel_utils.py to kernel_utils.cpython-36.pyc
byte-compiling build/bdist.macosx-10.7-x86_64/egg/dwd/sim_fun.py to sim_fun.cpython-36.pyc
byte-compiling build/bdist.macosx-10.7-x86_64/egg/dwd/gen_kern_dwd.py to gen_kern_dwd.cpython-36.pyc
byte-compiling build/bdist.macosx-10.7-x86_64/egg/dwd/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.macosx-10.7-x86_64/egg/dwd/utils.py to utils.cpython-36.pyc
byte-compiling build/bdist.macosx-10.7-x86_64/egg/dwd/dwd.py to dwd.cpython-36.pyc
byte-compiling build/bdist.macosx-10.7-x86_64/egg/dwd/cv.py to cv.cpython-36.pyc
byte-compiling build/bdist.macosx-10.7-x86_64/egg/dwd/kern_md.py to kern_md.cpython-36.pyc
byte-compiling build/bdist.macosx-10.7-x86_64/egg/dwd/svm.py to svm.cpython-36.pyc
byte-compiling build/bdist.macosx-10.7-x86_64/egg/dwd/viz.py to viz.cpython-36.pyc
byte-compiling build/bdist.macosx-10.7-x86_64/egg/dwd/gen_dwd.py to gen_dwd.cpython-36.pyc
creating build/bdist.macosx-10.7-x86_64/egg/EGG-INFO
copying dwd.egg-info/PKG-INFO -> build/bdist.macosx-10.7-x86_64/egg/EGG-INFO
copying dwd.egg-info/SOURCES.txt -> build/bdist.macosx-10.7-x86_64/egg/EGG-INFO
copying dwd.egg-info/dependency_links.txt -> build/bdist.macosx-10.7-x86_64/egg/EGG-INFO
copying dwd.egg-info/not-zip-safe -> build/bdist.macosx-10.7-x86_64/egg/EGG-INFO
copying dwd.egg-info/requires.txt -> build/bdist.macosx-10.7-x86_64/egg/EGG-INFO
copying dwd.egg-info/top_level.txt -> build/bdist.macosx-10.7-x86_64/egg/EGG-INFO
creating dist
creating 'dist/dwd-0.0.1-py3.6.egg' and adding 'build/bdist.macosx-10.7-x86_64/egg' to it
removing 'build/bdist.macosx-10.7-x86_64/egg' (and everything under it)
Processing dwd-0.0.1-py3.6.egg
creating /anaconda3/lib/python3.6/site-packages/dwd-0.0.1-py3.6.egg
Extracting dwd-0.0.1-py3.6.egg to /anaconda3/lib/python3.6/site-packages
Adding dwd 0.0.1 to easy-install.pth file

Installed /anaconda3/lib/python3.6/site-packages/dwd-0.0.1-py3.6.egg
Processing dependencies for dwd==0.0.1
Searching for sklearn
Reading https://pypi.org/simple/sklearn/
Downloading https://files.pythonhosted.org/packages/1e/7a/dbb3be0ce9bd5c8b7e3d87328e79063f8b263b2b1bfa4774cb1147bfcd3f/sklearn-0.0.tar.gz#sha256=e23001573aa194b834122d2b9562459bf5ae494a2d59ca6b8aa22c85a44c0e31
Best match: sklearn 0.0
Processing sklearn-0.0.tar.gz
Writing /var/folders/nw/sw0s7pqd3jv9skdz9xlyjt3c0000gn/T/easy_install-gbiu1h52/sklearn-0.0/setup.cfg
Running sklearn-0.0/setup.py -q bdist_egg --dist-dir /var/folders/nw/sw0s7pqd3jv9skdz9xlyjt3c0000gn/T/easy_install-gbiu1h52/sklearn-0.0/egg-dist-tmp-c3s5ycn7
file wheel-platform-tag-is-broken-on-empty-wheels-see-issue-141.py (for module wheel-platform-tag-is-broken-on-empty-wheels-see-issue-141) not found
file wheel-platform-tag-is-broken-on-empty-wheels-see-issue-141.py (for module wheel-platform-tag-is-broken-on-empty-wheels-see-issue-141) not found
file wheel-platform-tag-is-broken-on-empty-wheels-see-issue-141.py (for module wheel-platform-tag-is-broken-on-empty-wheels-see-issue-141) not found
warning: install_lib: 'build/lib' does not exist -- no Python modules to install

creating /anaconda3/lib/python3.6/site-packages/sklearn-0.0-py3.6.egg
Extracting sklearn-0.0-py3.6.egg to /anaconda3/lib/python3.6/site-packages
Adding sklearn 0.0 to easy-install.pth file

Installed /anaconda3/lib/python3.6/site-packages/sklearn-0.0-py3.6.egg
Searching for cvxpy
Reading https://pypi.org/simple/cvxpy/
Downloading https://files.pythonhosted.org/packages/09/a4/bd2585aa6024393fe4ed9346a9b66500e8e0e054d0ff4356c094fb7fbf41/cvxpy-1.0.25-cp36-cp36m-macosx_10_7_x86_64.whl#sha256=c2400927cceb170f96c1c97ad7faacaf92e941bbddb06b837d4d51fedbd7b192
Best match: cvxpy 1.0.25
Processing cvxpy-1.0.25-cp36-cp36m-macosx_10_7_x86_64.whl
Installing cvxpy-1.0.25-cp36-cp36m-macosx_10_7_x86_64.whl to /anaconda3/lib/python3.6/site-packages
writing requirements to /anaconda3/lib/python3.6/site-packages/cvxpy-1.0.25-py3.6-macosx-10.7-x86_64.egg/EGG-INFO/requires.txt
Adding cvxpy 1.0.25 to easy-install.pth file

Installed /anaconda3/lib/python3.6/site-packages/cvxpy-1.0.25-py3.6-macosx-10.7-x86_64.egg
Searching for scs>=1.1.3
Reading https://pypi.org/simple/scs/
Downloading https://files.pythonhosted.org/packages/f2/6e/dbdd778c64c1920ae357a2013ea655d65a1f8b60f397d6e5549e4aafe8ec/scs-2.1.1-2.tar.gz#sha256=f816cfe3d4b4cff3ac2b8b96588c5960ddd2a3dc946bda6b09db04e7bc6577f2
Best match: scs 2.1.1.post2
Processing scs-2.1.1-2.tar.gz
Writing /var/folders/nw/sw0s7pqd3jv9skdz9xlyjt3c0000gn/T/easy_install-7l1z51qc/scs-2.1.1-2/setup.cfg
Running scs-2.1.1-2/setup.py -q bdist_egg --dist-dir /var/folders/nw/sw0s7pqd3jv9skdz9xlyjt3c0000gn/T/easy_install-7l1z51qc/scs-2.1.1-2/egg-dist-tmp-0yx5ifwe
Namespace(blas64=False, extraverbose=False, float32=False, gpu=False, int32=False, scs=False)
/anaconda3/lib/python3.6/site-packages/setuptools/dist.py:484: UserWarning: The version specified ('2.1.1_2') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
  "details." % self.metadata.version
mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/anaconda3/include']
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/anaconda3/include']
{'libraries': ['mkl_rt', 'pthread'], 'library_dirs': ['/anaconda3/lib'], 'define_macros': [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)], 'include_dirs': ['/anaconda3/include']}
{'libraries': ['mkl_rt', 'pthread'], 'library_dirs': ['/anaconda3/lib'], 'define_macros': [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)], 'include_dirs': ['/anaconda3/include']}
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
error: Setup script exited with error: Command "gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/anaconda3/include -arch x86_64 -I/anaconda3/include -arch x86_64 -DPYTHON -DCTRLC=1 -DDLONG=1 -DCOPYAMATRIX -DUSE_LAPACK -DSCIPY_MKL_H -DHAVE_CBLAS -DSCIPY_MKL_H -DHAVE_CBLAS -Iscs/include -Iscs/linsys -Iscs/linsys/direct/ -Iscs/linsys/direct/external/ -I/anaconda3/lib/python3.6/site-packages/numpy/core/include -I/anaconda3/include -I/anaconda3/include -I/anaconda3/include/python3.6m -c scs/src/linalg.c -o build/temp.macosx-10.7-x86_64-3.6/scs/src/linalg.o -O3" failed with exit status 1

**Comment by idc9** [comment]
I'm not 100% sure what's going on. My best guess is there is a problem with installing cvxpy.

Can you try installing cvxpy (https://www.cvxpy.org/install/index.html)? Do you get the same error? If cvxpy installs, try re-installing dwd and let me know what happens.

If it is a problem with cvxpy then try posting an issue on their github. In this case, I can make cvxpy an optional install (only https://github.com/idc9/dwd/blob/master/dwd/dwd.py and the svm class use cvxpy so most of the functionality of the package will still work).
